### ISSUE TITLE
仅在失败时走代理

### ISSUE THREAD

**Issue by Ghost-chu** [ArtformGames/BungeeAuthProxy#1]
### **Description**

考虑到目前仍然有相当的时间可以直连，建议仅在失败时才回退到代理请求。

### **Source**

N/A

### **Examples** _(Optional)_

N/A

### **AddItional details**

N/A

**Comment by CarmJos** [comment]
似乎没有太大必要，既然可以走代理为何不走代理呢？验证请求并不是强绑定与来源服务器IP的吧。
